Repository Nexters/myply, pull requests merged in 2022-08, with the labels that each got.

#44 fix: wire and gopls bug
  .gitignore
  .vscode/settings.json
Labels: bug

#42 Youtube Search
  .env.local
  application/controller/.gitkeep
  application/controller/index.go
  application/controller/musics.go
  application/router/index.go
  application/router/musics.go
  application/server.go
  application/wire_gen.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domain/entity/.gitkeep
  domain/entity/musics.go
  domain/repository/.gitkeep
  domain/repository/musics.go
  domain/service/.gitkeep
  domain/service/index.go
  domain/service/musics.go
  go.mod
  go.sum
  infrastructure/clients/.gitkeep
  infrastructure/clients/index.go
  infrastructure/clients/youtube.go
  infrastructure/configs/config.go
  infrastructure/persistence/index.go
  infrastructure/persistence/musics.go
Labels: task, infra

#48 Introduce mongo cache
  .env.local
  application/controller/musics.go
  application/server.go
  application/wire_gen.go
  domain/musics/entity.go
  domain/musics/index.go
  domain/musics/repository.go
  domain/musics/service.go
  domain/repository/musics.go
  domain/service/musics.go
  domain/tag/tag.entity.go
  go.mod
  go.sum
  infrastructure/clients/youtube.go
  infrastructure/configs/config.go
  infrastructure/persistence/cache/mongo.go
  infrastructure/persistence/db/mongo.go
  infrastructure/persistence/index.go
  infrastructure/persistence/musics.go
Labels: task, infra

#55 feat: retrieve playlist
  application/controller/musics.go
  application/router/musics.go
  domain/musics/repository.go
  domain/musics/service.go
  infrastructure/clients/youtube.go
  infrastructure/persistence/musics.go
Labels: task

#61 Feature/60/add pagination
  Makefile
  application/controller/musics.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domain/musics/index.go
  domain/musics/repository.go
  domain/musics/service.go
  infrastructure/clients/youtube.go
  infrastructure/clients/youtube_test.go
  infrastructure/configs/config.go
  infrastructure/persistence/cache/mongo.go
  infrastructure/persistence/member.go
  infrastructure/persistence/musics.go
Labels: bug, feature, infra

#63 Feature/62/refactor queries to query
  application/controller/musics.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domain/musics/index.go
  domain/musics/service.go
  infrastructure/persistence/musics.go
Labels: task, refactor

#65 fix: replaced mock data with real data
  application/controller/memo.go
  application/wire_gen.go
  domain/memos/entity.go
  domain/memos/repository.go
  domain/memos/service.go
  domain/musics/repository.go
  domain/musics/service.go
  infrastructure/clients/youtube.go
  infrastructure/persistence/memo.go
  infrastructure/persistence/musics.go
Labels: bug, task

#67 Feature/66/get users memo list
  application/controller/memo.go
  application/router/memo.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domain/memos/entity.go
  domain/memos/entity_test.go
  domain/memos/repository.go
  domain/memos/service.go
  domain/musics/entity.go
  domain/musics/errors.go
  domain/musics/repository.go
  domain/musics/service.go
  infrastructure/clients/youtube.go
  infrastructure/clients/youtube_test.go
  infrastructure/persistence/member.go
  infrastructure/persistence/memo.go
  infrastructure/persistence/musics.go
Labels: bug, task

#70 feat: add tag preference endpoint
  application/controller/musics.go
  application/router/musics.go
  application/wire_gen.go
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  domain/member/entity.go
Labels: feature

#76 Feature/75/bug fix
  infrastructure/clients/youtube.go
  infrastructure/persistence/musics.go
Labels: bug
